name: Dependabot auto-merge
on:
  check_run:
    types:
      - completed
  
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.actor == 'dependabot[bot]' && github.event.check_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm test
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
      - name: auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "${{ steps.pr_details.outputs.pr_url }}"