name: Dependabot auto-merge
on:
  workflow_run:
    workflows: [ "Build", "Lint", "Test", "Typecheck" ]
    types:
      - completed
  
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}